version: '3'

services:
    rabbbitmq: 
        image: 'rabbitmq:3-management-alpine'
        container_name: 'rabbitHOLD'
        ports: 
            - "5672:5672"
        networks:
            - rabbitmq_go_net
networks:
  rabbitmq_go_net:
    driver: bridge
